const std = @import("std");

const report_data = @import("report_data.zig");

const Allocator = std.mem.Allocator;
const Io = std.Io;
const Writer = std.Io.Writer;
pub const MetricsReportData = report_data.MetricsReportData;
pub const MetricValue = report_data.MetricValue;
pub const RenderError = Allocator.Error || error{
    EmptyMetricLabel,
    EmptySectionTitle,
    InvalidReportTitle,
};

pub const MetricsExportOptions = struct {
    title: []const u8 = "ArchUnitZig Metrics Report",
    include_timestamp: bool = true,
    custom_css: ?[]const u8 = null,
};

/// Renders one complete offline HTML document. A sorted clone preserves caller-owned data order
/// while making output canonical for equal report content.
pub fn toHtml(
    allocator: Allocator,
    io: Io,
    data: *const MetricsReportData,
    options: MetricsExportOptions,
) RenderError![]u8 {
    if (!hasText(options.title)) return error.InvalidReportTitle;
    var sorted = try data.clone(allocator);
    defer sorted.deinit(allocator);
    sorted.sort();

    var output: Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;
    try tryWrite(writer, "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
    try tryWrite(writer, "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>");
    try writeHtml(writer, options.title);
    try tryWrite(writer, "</title><style>");
    try tryWrite(writer, default_css);
    if (options.custom_css) |custom_css| {
        try tryWrite(writer, "\n");
        try writeSafeCss(writer, custom_css);
    }
    try tryWrite(writer, "</style></head><body><header><h1>");
    try writeHtml(writer, options.title);
    try tryWrite(writer, "</h1>");
    if (options.include_timestamp) try writeTimestamp(writer, io);
    try tryWrite(writer, "</header><main>");
    if (sorted.items().len == 0) {
        try tryWrite(writer, "<div class=\"empty\">No metric data.</div>");
    } else {
        for (sorted.items()) |section| try writeSection(writer, section);
    }
    try tryWrite(writer, "</main><footer>Generated by ArchUnitZig metrics reporting</footer></body></html>");
    return output.toOwnedSlice();
}

const default_css =
    ":root{color-scheme:light;font-family:Inter,system-ui,sans-serif}" ++
    "*{box-sizing:border-box}body{margin:0;color:#172033;background:#f5f7fb}" ++
    "header{padding:28px 36px;color:#fff;background:#13294b}" ++
    "header h1{margin:0 0 6px;font-size:28px}.timestamp{margin:0;color:#d7e3f4}" ++
    "main{max-width:1080px;margin:0 auto;padding:28px 36px 48px}" ++
    "section{margin:0 0 28px}h2{font-size:20px}" ++
    "table{width:100%;border-collapse:collapse;background:#fff}" ++
    "th,td{padding:9px 11px;border:1px solid #d8deea;text-align:left}" ++
    "th{background:#eaf0f8}.value{font-family:Consolas,monospace;text-align:right}" ++
    ".empty{padding:16px;border:1px solid #d8deea;background:#fff}" ++
    "footer{padding:18px 36px;color:#536079;text-align:center}";

fn writeSection(writer: *Writer, section: report_data.MetricsReportSection) RenderError!void {
    try tryWrite(writer, "<section data-kind=\"");
    try tryWrite(writer, @tagName(section.kind));
    try tryWrite(writer, "\"><h2>");
    try writeHtml(writer, section.title);
    try tryWrite(writer, "</h2>");
    if (section.items().len == 0) {
        try tryWrite(writer, "<div class=\"empty\">No metric values in this section.</div></section>");
        return;
    }
    try tryWrite(writer, "<table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>");
    for (section.items()) |entry| {
        try tryWrite(writer, "<tr><td>");
        try writeHtml(writer, entry.label);
        try tryWrite(writer, "</td><td class=\"value\" data-value-kind=\"");
        try tryWrite(writer, @tagName(std.meta.activeTag(entry.value)));
        try tryWrite(writer, "\">");
        try writeMetricValue(writer, entry.value);
        try tryWrite(writer, "</td></tr>");
    }
    try tryWrite(writer, "</tbody></table></section>");
}

fn writeMetricValue(writer: *Writer, value: MetricValue) RenderError!void {
    switch (value) {
        .signed => |number| writer.print("{d}", .{number}) catch return error.OutOfMemory,
        .unsigned => |number| writer.print("{d}", .{number}) catch return error.OutOfMemory,
        .floating => |number| writer.print("{d}", .{number}) catch return error.OutOfMemory,
    }
}

fn writeTimestamp(writer: *Writer, io: Io) RenderError!void {
    const unix_seconds = std.Io.Clock.real.now(io).toSeconds();
    try tryWrite(writer, "<p class=\"timestamp\">Generated: ");
    if (unix_seconds < 0) {
        writer.print("Unix second {d}", .{unix_seconds}) catch return error.OutOfMemory;
    } else {
        const epoch_seconds = std.time.epoch.EpochSeconds{ .secs = @intCast(unix_seconds) };
        const year_day = epoch_seconds.getEpochDay().calculateYearDay();
        const month_day = year_day.calculateMonthDay();
        const day_seconds = epoch_seconds.getDaySeconds();
        writer.print(
            "{d:0>4}-{d:0>2}-{d:0>2}T{d:0>2}:{d:0>2}:{d:0>2}Z",
            .{
                year_day.year,
                month_day.month.numeric(),
                month_day.day_index + 1,
                day_seconds.getHoursIntoDay(),
                day_seconds.getMinutesIntoHour(),
                day_seconds.getSecondsIntoMinute(),
            },
        ) catch return error.OutOfMemory;
    }
    try tryWrite(writer, "</p>");
}

fn writeHtml(writer: *Writer, value: []const u8) RenderError!void {
    for (value) |byte| switch (byte) {
        '&' => try tryWrite(writer, "&amp;"),
        '<' => try tryWrite(writer, "&lt;"),
        '>' => try tryWrite(writer, "&gt;"),
        '"' => try tryWrite(writer, "&quot;"),
        '\'' => try tryWrite(writer, "&#39;"),
        else => writer.writeByte(byte) catch return error.OutOfMemory,
    };
}

/// CSS is intentionally not HTML-escaped because it must remain executable CSS. Neutralizing every
/// case-insensitive closing style token prevents it from escaping the one embedded style element.
fn writeSafeCss(writer: *Writer, value: []const u8) RenderError!void {
    var index: usize = 0;
    while (index < value.len) {
        if (index + "</style".len <= value.len and
            std.ascii.eqlIgnoreCase(value[index .. index + "</style".len], "</style"))
        {
            try tryWrite(writer, "<\\/style");
            index += "</style".len;
            continue;
        }
        writer.writeByte(value[index]) catch return error.OutOfMemory;
        index += 1;
    }
}

fn tryWrite(writer: *Writer, value: []const u8) RenderError!void {
    writer.writeAll(value) catch return error.OutOfMemory;
}

fn hasText(value: []const u8) bool {
    return std.mem.trim(u8, value, " \t\r\n\x0b\x0c").len != 0;
}

fn makeEscapingData(allocator: Allocator) !MetricsReportData {
    var section = try report_data.MetricsReportSection.init(
        allocator,
        .custom,
        "Risk <&> \"section\"",
    );
    var section_owned = true;
    errdefer if (section_owned) section.deinit(allocator);
    try section.append(allocator, "<script>alert('x')</script>", .{ .signed = -2 });
    try section.append(allocator, "ratio", .{ .floating = 0.25 });
    var data = MetricsReportData{};
    errdefer data.deinit(allocator);
    try data.appendSectionMove(allocator, &section);
    section_owned = false;
    return data;
}

test "HTML renderer is escaped offline deterministic and preserves every typed value" {
    var data = try makeEscapingData(std.testing.allocator);
    defer data.deinit(std.testing.allocator);
    const options = MetricsExportOptions{
        .title = "Team <Metrics> & \"quality\"",
        .include_timestamp = false,
        .custom_css = ".risk { color: red; } </StYlE><script>bad()</script>",
    };
    const first = try toHtml(std.testing.allocator, std.testing.io, &data, options);
    defer std.testing.allocator.free(first);
    const second = try toHtml(std.testing.allocator, std.testing.io, &data, options);
    defer std.testing.allocator.free(second);

    try std.testing.expectEqualStrings(first, second);
    try std.testing.expect(std.mem.startsWith(u8, first, "<!DOCTYPE html><html lang=\"en\">"));
    try std.testing.expect(std.mem.endsWith(u8, first, "</body></html>"));
    for ([_][]const u8{
        "<title>Team &lt;Metrics&gt; &amp; &quot;quality&quot;</title>",
        "Risk &lt;&amp;&gt; &quot;section&quot;",
        "&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;",
        "data-value-kind=\"signed\">-2</td>",
        "data-value-kind=\"floating\">0.25</td>",
        ".risk { color: red; } <\\/style><script>bad()",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, first, needle) != null);
    try std.testing.expect(std.mem.indexOf(u8, first, "Generated:") == null);
    try std.testing.expect(std.mem.indexOf(u8, first, "</style><script>") == null);
    try std.testing.expect(std.mem.indexOf(u8, first, "https://") == null);
    try std.testing.expect(std.mem.indexOf(u8, first, "http://") == null);
    try std.testing.expect(std.mem.indexOf(u8, first, "<link") == null);
}

test "empty report and optional UTC timestamp are explicit" {
    var data = MetricsReportData{};
    defer data.deinit(std.testing.allocator);
    const without_time = try toHtml(
        std.testing.allocator,
        std.testing.io,
        &data,
        .{ .include_timestamp = false },
    );
    defer std.testing.allocator.free(without_time);
    try std.testing.expect(std.mem.indexOf(u8, without_time, "No metric data.") != null);

    const with_time = try toHtml(std.testing.allocator, std.testing.io, &data, .{});
    defer std.testing.allocator.free(with_time);
    try std.testing.expect(std.mem.indexOf(u8, with_time, "<p class=\"timestamp\">Generated: ") != null);
    try std.testing.expect(std.mem.indexOf(u8, with_time, "Z</p>") != null);
    try std.testing.expectError(
        error.InvalidReportTitle,
        toHtml(std.testing.allocator, std.testing.io, &data, .{ .title = " \t" }),
    );
}

fn exerciseAllocationFailures(allocator: Allocator) !void {
    var data = try makeEscapingData(allocator);
    defer data.deinit(allocator);
    const html = try toHtml(
        allocator,
        std.testing.io,
        &data,
        .{ .include_timestamp = false, .custom_css = "body{color:red}" },
    );
    defer allocator.free(html);
}

test "HTML rendering releases sorted clones and partial output allocations" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        exerciseAllocationFailures,
        .{},
    );
}
