const std = @import("std");

const escaping = @import("escaping.zig");
const json_renderer = @import("json_renderer.zig");
const report = @import("../projection/report.zig");
const support = @import("support.zig");
const text_renderers = @import("text_renderers.zig");

const Allocator = std.mem.Allocator;
const Writer = std.Io.Writer;
pub const GraphReportSnapshot = report.GraphReportSnapshot;
pub const RenderError = text_renderers.RenderError;

pub fn toHtml(allocator: Allocator, snapshot: *const GraphReportSnapshot) RenderError![]u8 {
    const dot = try text_renderers.toDot(allocator, snapshot);
    defer allocator.free(dot);
    const mermaid = try text_renderers.toMermaid(allocator, snapshot);
    defer allocator.free(mermaid);
    const d2 = try text_renderers.toD2(allocator, snapshot);
    defer allocator.free(d2);
    const json = try json_renderer.toJson(allocator, snapshot);
    defer allocator.free(json);

    var output: Writer.Allocating = .init(allocator);
    errdefer output.deinit();
    const writer = &output.writer;
    writer.writeAll(document_head) catch return error.OutOfMemory;
    escaping.writeHtml(writer, snapshot.title) catch return error.OutOfMemory;
    writer.writeAll("</title></head><body><header><h1>") catch return error.OutOfMemory;
    escaping.writeHtml(writer, snapshot.title) catch return error.OutOfMemory;
    writer.writeAll(
        "</h1><p>Generated by ArchUnitZig graph reporting</p></header><main>",
    ) catch return error.OutOfMemory;
    writeSummary(writer, snapshot) catch return error.OutOfMemory;
    writeNodes(writer, snapshot) catch return error.OutOfMemory;
    writeDependencies(writer, snapshot) catch return error.OutOfMemory;
    writer.writeAll("<section><h2>Portable sources</h2>") catch return error.OutOfMemory;
    writeSource(writer, "Mermaid", mermaid) catch return error.OutOfMemory;
    writeSource(writer, "DOT", dot) catch return error.OutOfMemory;
    writeSource(writer, "D2", d2) catch return error.OutOfMemory;
    writeSource(writer, "JSON snapshot", json) catch return error.OutOfMemory;
    writer.writeAll("</section></main></body></html>") catch return error.OutOfMemory;
    return output.toOwnedSlice();
}

const document_head =
    "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">" ++
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">" ++
    "<style>" ++
    ":root{color-scheme:light;font-family:Inter,Arial,sans-serif}" ++
    "body{margin:0;color:#172033;background:#f5f7fb}" ++
    "header{padding:28px 36px;color:#fff;background:#13294b}" ++
    "header h1{margin:0 0 6px;font-size:28px}header p{margin:0;color:#d7e3f4}" ++
    "main{max-width:1180px;margin:0 auto;padding:28px 36px 48px}" ++
    "h2{margin-top:32px;font-size:20px}" ++
    ".summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}" ++
    ".metric{padding:16px;border:1px solid #d8deea;border-radius:8px;background:#fff}" ++
    ".metric strong{display:block;font-size:26px;color:#13294b}" ++
    "table{width:100%;border-collapse:collapse;background:#fff}" ++
    "th,td{padding:9px 11px;border:1px solid #d8deea;text-align:left}" ++
    "th{background:#eaf0f8}.external-edge{border-left:4px dashed #64748b}" ++
    ".resource-edge{border-left:4px solid #2563eb;background:#eff6ff}" ++
    "code,pre{font-family:Consolas,monospace}" ++
    "pre{overflow:auto;padding:16px;color:#e7edf7;background:#101827;border-radius:8px}" ++
    "details{margin:12px 0}summary{cursor:pointer;font-weight:700}" ++
    ".empty{padding:16px;border:1px solid #d8deea;background:#fff}" ++
    "@media(max-width:760px){.summary{grid-template-columns:repeat(2,1fr)}}" ++
    "</style><title>";

fn writeSummary(writer: *Writer, snapshot: *const GraphReportSnapshot) Writer.Error!void {
    try writer.writeAll("<section class=\"summary\" aria-label=\"Graph summary\">");
    try writeMetric(writer, snapshot.summary.node_count, "Nodes");
    try writeMetric(writer, snapshot.summary.edge_count, "Aggregated edges");
    try writeMetric(writer, snapshot.summary.raw_edge_count, "Raw edges");
    try writeMetric(writer, snapshot.summary.external_edge_count, "External edges");
    try writer.writeAll("</section>");
}

fn writeMetric(writer: *Writer, value: usize, label: []const u8) Writer.Error!void {
    try writer.print("<div class=\"metric\"><strong>{d}</strong>", .{value});
    try escaping.writeHtml(writer, label);
    try writer.writeAll("</div>");
}

fn writeNodes(writer: *Writer, snapshot: *const GraphReportSnapshot) Writer.Error!void {
    try writer.writeAll("<section><h2>Nodes</h2><table><thead><tr><th>ID</th><th>Label</th></tr></thead><tbody>");
    for (snapshot.nodes) |node| {
        try writer.writeAll("<tr><td><code>");
        try escaping.writeHtml(writer, node.id);
        try writer.writeAll("</code></td><td><code>");
        try escaping.writeHtml(writer, node.label);
        try writer.writeAll("</code></td></tr>");
    }
    try writer.writeAll("</tbody></table></section>");
}

fn writeDependencies(writer: *Writer, snapshot: *const GraphReportSnapshot) Writer.Error!void {
    try writer.writeAll("<section><h2>Dependencies</h2>");
    if (snapshot.edges.len == 0) {
        try writer.writeAll("<div class=\"empty\">No dependency edges matched this graph query.</div></section>");
        return;
    }
    try writer.writeAll(
        "<table><thead><tr><th>Source</th><th>Target</th><th>Count</th><th>External</th>" ++
            "<th>Import kinds</th><th>Target classes</th><th>Availability</th></tr></thead><tbody>",
    );
    for (snapshot.edges) |edge| {
        try writer.writeAll("<tr");
        if (edge.external or support.edgeIsResource(edge.target_classes)) {
            try writer.writeAll(" class=\"");
            if (edge.external) try writer.writeAll("external-edge");
            if (edge.external and support.edgeIsResource(edge.target_classes)) try writer.writeByte(' ');
            if (support.edgeIsResource(edge.target_classes)) try writer.writeAll("resource-edge");
            try writer.writeByte('"');
        }
        try writer.writeAll("><td><code>");
        try escaping.writeHtml(writer, edge.source);
        try writer.writeAll("</code></td><td><code>");
        try escaping.writeHtml(writer, edge.target);
        try writer.print("</code></td><td>{d}</td><td>{s}</td><td>", .{
            edge.count,
            if (edge.external) "yes" else "no",
        });
        try support.writeImportKinds(writer, edge.import_kinds, ", ");
        try writer.writeAll("</td><td>");
        try support.writeTargetClasses(writer, edge.target_classes, ", ");
        try writer.writeAll("</td><td>");
        try support.writeTargetAvailabilities(writer, edge.target_availabilities, ", ");
        try writer.writeAll("</td></tr>");
    }
    try writer.writeAll("</tbody></table></section>");
}

fn writeSource(writer: *Writer, name: []const u8, source: []const u8) Writer.Error!void {
    try writer.writeAll("<details><summary>");
    try escaping.writeHtml(writer, name);
    try writer.writeAll("</summary><pre>");
    try escaping.writeHtml(writer, source);
    try writer.writeAll("</pre></details>");
}

test "HTML renderer is one offline escaped document with complete metadata and sources" {
    var snapshot = try @import("test_snapshot.zig").make(std.testing.allocator);
    defer snapshot.deinit(std.testing.allocator);
    const rendered = try toHtml(std.testing.allocator, &snapshot);
    defer std.testing.allocator.free(rendered);

    try std.testing.expect(std.mem.startsWith(u8, rendered, "<!DOCTYPE html><html lang=\"en\">"));
    try std.testing.expect(std.mem.endsWith(u8, rendered, "</body></html>"));
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, rendered, "<html"));
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, rendered, "</html>"));
    for ([_][]const u8{
        "<title>Architecture &lt;Main&gt;\r\n&quot;quoted&quot;</title>",
        "<strong>4</strong>Nodes",
        "app/&quot;api&quot;\n.zig",
        "domain&lt;&amp;&gt;.zig",
        "class=\"resource-edge\"",
        "class=\"external-edge\"",
        "embedded_file",
        "compiler",
        "unresolved",
        "<summary>Mermaid</summary>",
        "<summary>DOT</summary>",
        "<summary>D2</summary>",
        "<summary>JSON snapshot</summary>",
    }) |needle| try std.testing.expect(std.mem.indexOf(u8, rendered, needle) != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "https://") == null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "http://") == null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "<script") == null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "<link") == null);
}

test "empty HTML snapshot renders an explicit empty dependency state" {
    const empty_nodes = try std.testing.allocator.alloc(report.GraphReportNode, 0);
    const empty_edges = try std.testing.allocator.alloc(report.GraphReportEdge, 0);
    var snapshot = report.GraphReportSnapshot{
        .title = try std.testing.allocator.dupe(u8, "Empty"),
        .nodes = empty_nodes,
        .edges = empty_edges,
        .summary = .{ .node_count = 0, .edge_count = 0, .raw_edge_count = 0, .external_edge_count = 0 },
    };
    defer snapshot.deinit(std.testing.allocator);
    const rendered = try toHtml(std.testing.allocator, &snapshot);
    defer std.testing.allocator.free(rendered);
    try std.testing.expect(std.mem.indexOf(
        u8,
        rendered,
        "No dependency edges matched this graph query.",
    ) != null);
}

fn exerciseAllocationFailures(allocator: Allocator, snapshot: *const GraphReportSnapshot) RenderError!void {
    const rendered = try toHtml(allocator, snapshot);
    defer allocator.free(rendered);
}

test "HTML rendering and nested source rendering clean up every allocation failure" {
    var snapshot = try @import("test_snapshot.zig").make(std.testing.allocator);
    defer snapshot.deinit(std.testing.allocator);
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        exerciseAllocationFailures,
        .{&snapshot},
    );
}
