//! Public package root for ArchUnitZig.
//!
//! The rule-building API will be added incrementally as its contracts are implemented and tested.

const std = @import("std");
const assertion = @import("common/assertion.zig");
const common_error = @import("common/error.zig");
const extraction = @import("common/extraction.zig");
const file_rules = @import("files.zig");
const fluentapi = @import("common/fluentapi.zig");
const graph_reports = @import("graph.zig");
const matching = @import("common/matching.zig");
const layer_rules = @import("layers.zig");
const projection = @import("common/projection.zig");
const slice_rules = @import("slices.zig");
const testing_support = @import("testing.zig");

pub const Edge = extraction.Edge;
pub const BuildGraphMode = extraction.BuildGraphMode;
pub const ClassifiedReference = extraction.ClassifiedReference;
pub const ArchUnitError = common_error.ArchUnitError;
pub const Diagnostic = common_error.Diagnostic;
pub const DiagnosticCode = common_error.DiagnosticCode;
pub const DependencyReference = extraction.DependencyReference;
pub const DiagnosticKind = extraction.DiagnosticKind;
pub const EmptyTestViolation = assertion.EmptyTestViolation;
pub const FileDependencyViolation = assertion.FileDependencyViolation;
pub const FileInfo = file_rules.FileInfo;
pub const ExternalModuleDependencyViolation = assertion.ExternalModuleDependencyViolation;
pub const LayerDependencyViolation = assertion.LayerDependencyViolation;
pub const LayerPolicyKind = assertion.LayerPolicyKind;
pub const SliceDependencyViolation = assertion.SliceDependencyViolation;
pub const DependencyPolicyKind = layer_rules.DependencyPolicyKind;
pub const LayerDefinition = layer_rules.LayerDefinition;
pub const LayerError = layer_rules.LayerError;
pub const LayerPolicy = layer_rules.LayerPolicy;
pub const LayerBuilderError = layer_rules.BuilderError;
pub const LayerDefinitionBuilder = layer_rules.LayerDefinitionBuilder;
pub const LayerDependencyRuleBuilder = layer_rules.LayerDependencyRuleBuilder;
pub const LayeredArchitecture = layer_rules.LayeredArchitecture;
pub const ProjectLayerOptions = layer_rules.ProjectLayerOptions;
pub const CycleViolation = assertion.CycleViolation;
pub const CustomFileViolation = assertion.CustomFileViolation;
pub const EnumerationOptions = extraction.EnumerationOptions;
pub const ErrorCategory = common_error.ErrorCategory;
pub const ErrorContext = common_error.ErrorContext;
pub const FileResolutionStatus = extraction.FileResolutionStatus;
pub const FileResolutionInput = extraction.FileResolutionInput;
pub const FileBuilderError = file_rules.BuilderError;
pub const FilesScope = file_rules.FilesScope;
pub const FilesHaveNoCycles = file_rules.FilesHaveNoCycles;
pub const FilesMatchPattern = file_rules.FilesMatchPattern;
pub const FilesDependOnBuilder = file_rules.FilesDependOnBuilder;
pub const FilesDependOn = file_rules.FilesDependOn;
pub const FilesExternalModuleBuilder = file_rules.FilesExternalModuleBuilder;
pub const FilesExternalModules = file_rules.FilesExternalModules;
pub const FilesAdhereTo = file_rules.FilesAdhereTo;
pub const FilesShould = file_rules.FilesShould;
pub const FilesShouldNot = file_rules.FilesShouldNot;
pub const Graph = extraction.Graph;
pub const GraphReportEdge = graph_reports.GraphReportEdge;
pub const GraphReportNode = graph_reports.GraphReportNode;
pub const GraphReportSnapshot = graph_reports.GraphReportSnapshot;
pub const GraphReportSummary = graph_reports.GraphReportSummary;
pub const CollapseQuery = graph_reports.CollapseQuery;
pub const FocusQuery = graph_reports.FocusQuery;
pub const GraphQueryOptions = graph_reports.GraphQueryOptions;
pub const PatternCollapse = graph_reports.PatternCollapse;
pub const GraphNodeSelection = graph_reports.NodeSelection;
pub const GraphSnapshotError = graph_reports.GraphSnapshotError;
pub const GraphReportFormat = graph_reports.GraphReportFormat;
pub const GraphRenderError = graph_reports.GraphRenderError;
pub const GraphExportError = graph_reports.GraphExportError;
pub const GraphRenderer = graph_reports.GraphRenderer;
pub const GraphBuilderError = graph_reports.GraphBuilderError;
pub const ProjectGraphBuilder = graph_reports.ProjectGraphBuilder;
pub const ProjectGraphOptions = graph_reports.ProjectGraphOptions;
pub const ImportKind = extraction.ImportKind;
pub const ImportKinds = extraction.ImportKinds;
pub const ImportSummary = extraction.ImportSummary;
pub const LocatedProject = extraction.LocatedProject;
pub const Candidate = matching.Candidate;
pub const CheckOptions = fluentapi.CheckOptions;
pub const CustomFilePredicate = file_rules.CustomFilePredicate;
pub const Checkable = fluentapi.Checkable;
pub const CompilationUnitOverride = extraction.CompilationUnitOverride;
pub const CycleProjectionError = projection.CycleProjectionError;
pub const ExtractionOptions = extraction.ExtractionOptions;
pub const Filter = matching.Filter;
pub const MatchingMode = matching.MatchingMode;
pub const MapFunction = projection.MapFunction;
pub const MappedEdge = projection.MappedEdge;
pub const LogLevel = fluentapi.LogLevel;
pub const LoggingOptions = fluentapi.LoggingOptions;
pub const ModuleOrigin = extraction.ModuleOrigin;
pub const ModuleOverride = extraction.ModuleOverride;
pub const ModuleResolutionOverrides = extraction.ModuleResolutionOverrides;
pub const ModuleResolutionStatus = extraction.ModuleResolutionStatus;
pub const Mood = assertion.Mood;
pub const MatchingViolation = assertion.MatchingViolation;
pub const Pattern = matching.Pattern;
pub const ParseResult = extraction.ParseResult;
pub const NodeProjectionOptions = projection.NodeProjectionOptions;
pub const PatternSyntax = matching.PatternSyntax;
pub const PatternTarget = matching.PatternTarget;
pub const ProjectMarker = extraction.ProjectMarker;
pub const ProjectOptions = file_rules.ProjectOptions;
pub const ProjectedCycle = projection.ProjectedCycle;
pub const ProjectedCycles = projection.ProjectedCycles;
pub const ProjectedEdge = projection.ProjectedEdge;
pub const ProjectedEdges = projection.ProjectedEdges;
pub const ProjectedNode = projection.ProjectedNode;
pub const ProjectedNodes = projection.ProjectedNodes;
pub const ProjectionError = projection.ProjectionError;
pub const SliceLabels = slice_rules.SliceLabels;
pub const SliceProjection = slice_rules.SliceProjection;
pub const SliceProjectionError = slice_rules.SliceProjectionError;
pub const SliceSuffix = slice_rules.SliceSuffix;
pub const SliceBuilderError = slice_rules.SliceBuilderError;
pub const ProjectSliceOptions = slice_rules.ProjectSliceOptions;
pub const ProjectSlices = slice_rules.ProjectSlices;
pub const SliceDependencyRule = slice_rules.SliceDependencyRule;
pub const SlicesShould = slice_rules.SlicesShould;
pub const SlicesShouldNot = slice_rules.SlicesShouldNot;
pub const TechnicalCode = common_error.TechnicalCode;
pub const TechnicalError = common_error.TechnicalError;
pub const UserCode = common_error.UserCode;
pub const UserError = common_error.UserError;
pub const RegexFactory = matching.RegexFactory;
pub const ResolvedReference = extraction.ResolvedReference;
pub const ResolvedModuleReference = extraction.ResolvedModuleReference;
pub const ResolutionInput = extraction.ResolutionInput;
pub const ScopePattern = assertion.ScopePattern;
pub const FileScopePatterns = file_rules.ScopePatterns;
pub const SourceLocation = extraction.SourceLocation;
pub const SourceReferences = extraction.SourceReferences;
pub const Strictness = extraction.Strictness;
pub const SourceFiles = extraction.SourceFiles;
pub const SelectedFiles = file_rules.SelectedFiles;
pub const SyntaxDiagnostic = extraction.SyntaxDiagnostic;
pub const TopLevelDeclarationCounts = extraction.TopLevelDeclarationCounts;
pub const TargetAvailability = extraction.TargetAvailability;
pub const TargetAvailabilities = extraction.TargetAvailabilities;
pub const TargetClass = extraction.TargetClass;
pub const TargetClasses = extraction.TargetClasses;
pub const Violation = assertion.Violation;
pub const ViolationList = assertion.ViolationList;
pub const matchesAny = matching.matchesAny;
pub const matchesSelectors = matching.matchesSelectors;
pub const checkAll = fluentapi.checkAll;
pub const categoryOfError = common_error.categoryOf;
pub const classifyReference = extraction.classifyReference;
pub const clearGraphCache = extraction.clearGraphCache;
pub const locateProject = extraction.locateProject;
pub const normalizeGraph = extraction.normalizeGraph;
pub const parseSource = extraction.parseSource;
pub const projectEdges = projection.projectEdges;
pub const projectCycles = projection.projectCycles;
pub const projectInternalCycles = projection.projectInternalCycles;
pub const projectToNodes = projection.projectToNodes;
pub const resolveRelativeReference = extraction.resolveRelativeReference;
pub const resolveModuleReference = extraction.resolveModuleReference;
pub const validateModuleResolutionOverrides = extraction.validateModuleResolutionOverrides;
pub const enumerateSourceFiles = extraction.enumerateSourceFiles;
pub const extractProjectGraph = extraction.extractProjectGraph;
pub const files = file_rules.files;
pub const formatCyclePath = testing_support.formatCyclePath;
pub const ColorMode = testing_support.ColorMode;
pub const ColorOptions = testing_support.ColorOptions;
pub const FormattedViolation = testing_support.FormattedViolation;
pub const ViolationFactory = testing_support.ViolationFactory;
pub const ResultFactory = testing_support.ResultFactory;
pub const ResultOptions = testing_support.ResultOptions;
pub const TestResult = testing_support.TestResult;
pub const ViolationGroup = testing_support.ViolationGroup;
pub const ArchitectureAssertionError = testing_support.ArchitectureAssertionError;
pub const AssertionOptions = testing_support.AssertionOptions;
pub const assertAllPass = testing_support.assertAllPass;
pub const assertPasses = testing_support.assertPasses;
pub const expectPasses = testing_support.expectPasses;
pub const gatherMatchingFileViolations = file_rules.gatherMatchingFileViolations;
pub const gatherFileDependencyViolations = file_rules.gatherFileDependencyViolations;
pub const gatherCustomFileViolations = file_rules.gatherCustomFileViolations;
pub const gatherLayerDependencyViolations = layer_rules.gatherLayerDependencyViolations;
pub const gatherSliceDependencyViolations = slice_rules.gatherSliceDependencyViolations;
pub const layers = layer_rules.layers;
pub const projectLayers = layer_rules.projectLayers;
pub const guardEmptyTest = assertion.guardEmptyTest;
pub const ExternalModuleCategory = file_rules.ExternalModuleCategory;
pub const ExternalModuleCategories = file_rules.ExternalModuleCategories;
pub const defaultExternalModuleCategories = file_rules.defaultExternalModuleCategories;
pub const gatherExternalModuleDependencyViolations = file_rules.gatherExternalModuleDependencyViolations;
pub const identity = projection.identity;
pub const perEdge = projection.perEdge;
pub const perExternalEdge = projection.perExternalEdge;
pub const perInternalEdge = projection.perInternalEdge;
pub const projectFiles = file_rules.projectFiles;
pub const selectGraphNodes = graph_reports.selectGraphNodes;
pub const createGraphSnapshot = graph_reports.createGraphSnapshot;
pub const dependencyGraph = graph_reports.dependencyGraph;
pub const projectGraph = graph_reports.projectGraph;
pub const projectSliceEdges = slice_rules.projectSliceEdges;
pub const projectSliceLabels = slice_rules.projectSliceLabels;
pub const projectSlices = slice_rules.projectSlices;
pub const slices = slice_rules.slices;

test "public facade builds and runs pattern filters" {
    var filter = try RegexFactory.pathMatcher(
        std.testing.allocator,
        .{ .glob = "src/**/*.zig" },
    );
    defer filter.deinit();

    try std.testing.expect(try filter.matches(
        std.testing.allocator,
        .{ .path = "src\\domain\\model.zig" },
    ));
}

test "public native assertion helper runs a concrete rule in an ordinary test block" {
    var entry = try projectFiles(std.testing.allocator, .{
        .locator = "test/fixtures/files-selection",
    });
    defer entry.deinit();
    var root_scope = try entry.inFile(&.{"root.zig"});
    defer root_scope.deinit();
    var positive = try root_scope.should();
    defer positive.deinit();
    var terminal = try positive.haveName(.{ .glob = "root.zig" });
    defer terminal.deinit(std.testing.allocator);

    var output: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();
    var options = AssertionOptions.init(CheckOptions.init(std.testing.allocator, std.testing.io));
    options.check.clear_cache = true;
    options.failure_writer = &output.writer;
    try expectPasses(&terminal, options);
    try std.testing.expectEqual(@as(usize, 0), output.written().len);
}

test {
    _ = std.testing;
    _ = @import("common/assertion.zig");
    _ = @import("common/error.zig");
    _ = @import("common/extraction.zig");
    _ = @import("common/fluentapi.zig");
    _ = @import("common/matching.zig");
    _ = @import("common/projection.zig");
    _ = @import("files.zig");
    _ = @import("graph.zig");
    _ = @import("layers.zig");
    _ = @import("slices.zig");
    _ = @import("testing.zig");
}
